### ISSUE TITLE
[Bug] Knives don't give straw when breaking grass

### ISSUE THREAD

**Issue by SamHammie** [axperty/moredelight-fabric#12]
More Delight version 1.1.2
Minecraft version 1.20.1
Forge version 47.2.17

**Comment by axperty** [comment]
Hi SamHammie,

I just issued an updated fixing this bug, I appreciate your time reporting this bug, you can now harvest straw with wooden or stone knives. If you encounter any other issues, please let me know, feel free to open a new issue in this repository.

Have a good day,
Axperty.

---
If you want to support the creation of Minecraft mods, consider making a donation through [PayPal.](https://paypal.me/kevgelhorn)
