### ISSUE TITLE
Cooked Potato's recipe seems too good

### ISSUE THREAD

**Issue by NolanHewitt** [axperty/moredelight-fabric#5]
Getting nourishment and full saturation from just potato's seems incredibly good, makes it hard to justify any other food option when you can make this from a single food item. Perhaps it should give comfort instead of nourishment?

**Comment by axperty** [comment]
Hi Nolan Hewitt,

I'm currently working on an update for More Delight and the change you suggested will be considered, and I will do something about it.
If you have more suggestions feel free to let me know.

Have a good day,
Axperty.
