### ISSUE TITLE
There seems to be an issue with the recipe of the bread slices

### ISSUE THREAD

**Issue by AWAKEN-1** [axperty/moredelight-fabric#7]
MC:1.20.1
FORGE:47.2.20
mod:moredelight-1.1.0-1.20.1-forge.jar
![2024-04-12_18 45 53](https://github.com/axperty/moredelight-fabric/assets/77484596/b8913a05-845f-4a9f-b9e2-4486dd68a752)

**Comment by axperty** [comment]
Hi AWAKEN-1,

Seems like it's an issues with the tag that allows to use knifes to cut bread, I will be releasing an update that fixes it.
Thank you so much for reporting this error.

Have a good day,
Axperty.

**Comment by axperty** [comment]
Hi AWAKEN-1,

I just updated More Delight and it fixes this bug, you can see the changelog [here.](https://www.curseforge.com/minecraft/mc-mods/more-delight-forge/files/5258737)
I'd love to hear your feedback on More Delight as well, you can submit your suggestions [here.](https://docs.google.com/forms/d/e/1FAIpQLSfxAvbLhomY_n_ywtDTjRIutu8Mk0wQ1x4IOCQtyriqPkzFzw/viewform)

[Download for Forge](https://www.curseforge.com/minecraft/mc-mods/more-delight-forge) | [Download for Fabric](https://www.curseforge.com/minecraft/mc-mods/more-delight-fabric)

Have a good day,
Axperty.
