### ISSUE TITLE
Compatibility with Create: Food [Fabric]

### ISSUE THREAD

**Issue by ZachsRoom** [axperty/moredelight-fabric#8]
Both mods have recipes for sliced/diced potato and bread slices. Perhaps you could switch some of your recipes to use tags instead as well as adding items to tags to improve compatibility not for just this mod but potentially other mods as well?
 
![image](https://github.com/axperty/moredelight-fabric/assets/164839930/545f7b66-5c7a-40f1-a0c4-57458f86ac60)
![image](https://github.com/axperty/moredelight-fabric/assets/164839930/d5526c57-da44-46b4-b1d4-ab8bba2e43b9)

**Comment by axperty** [comment]
Hi ZachsRoom,

I'm currently working with adding tag support for all items in Fabric (I already did this in the Forge version), the problem I'm currently having is that some tags work only for Farmer's Delight [Fabric] and some work only for Farmer's Delight Refabricated, so I might have to release two versions for each mod.
I'll make sure bread slices and diced potatoes have tag support as well, there will be an update next week.

If you have any other suggestions or questions please let me know.

Have a good day,
Axperty.

**Comment by ZachsRoom** [comment]
> Hi ZachsRoom,
> 
> I'm currently working with adding tag support for all items in Fabric (I already did this in the Forge version), the problem I'm currently having is that some tags work only for Farmer's Delight [Fabric] and some work only for Farmer's Delight Refabricated, so I might have to release two versions for each mod. I'll make sure bread slices and diced potatoes have tag support as well, there will be an update next week.
> 
> If you have any other suggestions or questions please let me know.
> 
> Have a good day, Axperty.

![image](https://github.com/axperty/moredelight-fabric/assets/164839930/40c2fad9-3909-43b6-a6d1-f9495ad16fdf)

Just to caution you, he original fabric port of FD seems to be marked as deprecated so it most likely won't receive more updates in the future. Unless there's something I don't see, I don't think tagging for the original port gonna do much good.

**Comment by axperty** [comment]
Thank you so much for letting me know, I've been following the situation with that port, as far as I know the creator said that **it won't be updated anymore.**

I found that having **both ports installed** at the same time **makes all add-ons compatible** with Farmer's Delight Refabricated.

I'll start releasing updates for Farmer's Delight Refabricated and **slowly moving away from Farmer's Delight [Fabric].** I really want to add tags like I did with the Forge version, it makes everything so much easier.
You can check my [Discord](https://discord.com/invite/WTV8AqjaVY) for updates on More Delight and these kind of topics.

If you have more questions feel free to ask.

Have a good day,
Axperty.

**Comment by axperty** [comment]
Hi ZachsRoom,

I just updated **More Delight** adding tag support and now it works with **Create: Food,** thank you so much for your suggestion.

Have a good day,
Axperty.
